### PR TITLE
Add function to obtain an encoded image without writing to disk

### PR DESCRIPTION
**Pull request by animetosho**
I'm not sure if this has any interest, but I needed it, so I submit this should it be useful.

This PR adds a new `EncodeFrame` function. It's very similar to `Write` with the following differences:

* it takes in a VideoFrame instead of a clip (same applies to alpha)
* it returns the encoded data as a *bytes* object instead of writing it to disk
* as a result, file related arguments from `Write` aren't present in `EncodeFrame`

This is mostly useful when you need an image but don't want it to touch disk.  
Note that this function will likely return invalid data on VapourSynth prior to R65 (seems to be a bug there where data is cut off at the first null byte).

I haven't updated the documentation to cover this function; if you think this function is useful, I can update that as well.

I extracted a bunch of code into functions, since there's a lot of shared logic between `Write` and `EncodeFrame`. This will make the code diff seem larger than the actual changes made.

Whilst I was writing this, I did notice some things with the existing code, and had these questions:

* Is initialising [here](https://github.com/vapoursynth/vs-imwri/blob/3de419ff6e9d41a412ed5d98856db44b0fdd4615/src/imwri.cpp#L396) correct? According to [this](https://vapoursynth.com/doc/apireference.html#plugins), everything other than *VapourSynthPluginInit* can run in parallel. I imagine that `Magick::InitializeMagick` is setting up global state, which may not be thread safe.
* Is [this line](https://github.com/vapoursynth/vs-imwri/blob/3de419ff6e9d41a412ed5d98856db44b0fdd4615/src/imwri.cpp#L484C1-L484C47) redundant, considering it's already assigned [here](https://github.com/vapoursynth/vs-imwri/blob/3de419ff6e9d41a412ed5d98856db44b0fdd4615/src/imwri.cpp#L467)?

Thanks for reading.

### CODE REVIEW

**Comment by myrsloik** [comment]
Imwri is effectively obsolete because bestsource is a better image reader at this point.
Feel free to fork it. If you stick around and maintain it sanely I'll name you the official successor.

Magick::InitializeMagick should probably have a mutex, yes.
Sure looks like pointless double assignment

**Comment by animetosho** [comment]
I see, thanks for the response.

I'm mostly using this for the write functionality, which, to my knowledge, only imwri provides.  
Sorry if this is asking the obvious, but if this plugin is considered obsolete, I take it that there's no intention to support exporting images going forward?

As I need write functionality, I'll likely keep my fork around, but I have no intention of maintaining this project. Thanks for the offer nonetheless.

**Comment by myrsloik** [comment]
The export is very awkward when done inside a filter. Using vspipe>ffmpeg or passing the raw frame data to something else inside python works better.

**Comment by animetosho** [comment]
Interestingly enough, the point of this `EncodeFrame` function is to enable the frame to be passed onto something else in Python (and it also bypasses the filter aspect).

A lot of non-video things want interleaved RGB though, so you'd still need something to do the planar -> interleaved conversion (which you don't want to do in Python).

**Comment by animetosho** [comment]
> Imwri is effectively obsolete because bestsource is a better image reader at this point.

> The export is very awkward when done inside a filter. Using vspipe>ffmpeg or passing the raw frame data to something else inside python works better.

Might I suggest documenting this somewhere, e.g. update the imwri documentation page?  
I did do a little bit of research prior to this PR, but wasn't able to find that info.

Thanks

**Comment by myrsloik** [comment]
Done

**Pull request closed without merging**
